// lists.js
window.windowsFonts = [
  "Arial", "Arial Black", "Bahnschrift",
    "Calibri", "Cambria", "Cambria Math",
    "Candara", "Cascadia Code", "Cascadia Mono",
    "Comic Sans MS", "Consolas", "Constantia",
    "Corbel", "Courier New", "Ebrima",
    "Franklin Gothic Medium", "Gabriola", "Gadugi",
    "Georgia", "Impact", "Ink Free",
    "Javanese Text", "Leelawadee UI", "Lucida Console",
    "Lucida Sans Unicode", "Malgun Gothic", "Marlett",
    "Microsoft Himalaya", "Microsoft JhengHei", "Microsoft New Tai Lue",
    "Microsoft PhagsPa", "Microsoft Sans Serif", "Microsoft Tai Le",
    "Microsoft YaHei", "Microsoft Yi Baiti", "MingLiU-ExtB",
    "Mongolian Baiti", "MS Gothic", "MS PGothic",
    "MS UI Gothic", "MV Boli", "Myanmar Text",
    "Nirmala UI", "Palatino Linotype", "Segoe MDL2 Assets",
    "Segoe Print", "Segoe Script", "Segoe UI",
    "Segoe UI Black", "Segoe UI Emoji", "Segoe UI Historic",
    "Segoe UI Light", "Segoe UI Semibold", "Segoe UI Semilight",
    "Segoe UI Symbol", "SimSun", "Sitka Banner",
    "Sitka Display", "Sitka Heading", "Sitka Small",
    "Sitka Subheading", "Sitka Text", "Sylfaen",
    "Symbol", "Tahoma", "Times New Roman",
    "Trebuchet MS", "Verdana", "Webdings",
    "Wingdings", "Yu Gothic", "Yu Gothic UI"
];

window.cssColors = [
  "AliceBlue", "AntiqueWhite", "Aqua",
    "Aquamarine", "Azure", "Beige",
    "Bisque", "Black", "BlanchedAlmond",
    "Blue", "BlueViolet", "Brown",
    "BurlyWood", "CadetBlue", "Chartreuse",
    "Chocolate", "Coral", "CornflowerBlue",
    "Cornsilk", "Crimson", "Cyan",
    "DarkBlue", "DarkCyan", "DarkGoldenRod",
    "DarkGray", "DarkGreen", "DarkKhaki",
    "DarkMagenta", "DarkOliveGreen", "DarkOrange",
    "DarkOrchid", "DarkRed", "DarkSalmon",
    "DarkSeaGreen", "DarkSlateBlue", "DarkSlateGray",
    "DarkTurquoise", "DarkViolet", "DeepPink",
    "DeepSkyBlue", "DimGray", "DodgerBlue",
    "FireBrick", "FloralWhite", "ForestGreen",
    "Fuchsia", "Gainsboro", "GhostWhite",
    "Gold", "GoldenRod", "Gray",
    "Green", "GreenYellow", "HoneyDew",
    "HotPink", "IndianRed", "Indigo",
    "Ivory", "Khaki", "Lavender",
    "LavenderBlush", "LawnGreen", "LemonChiffon",
    "LightBlue", "LightCoral", "LightCyan",
    "LightGoldenRodYellow", "LightGray", "LightGreen",
    "LightPink", "LightSalmon", "LightSeaGreen",
    "LightSkyBlue", "LightSlateGray", "LightSteelBlue",
    "LightYellow", "Lime", "LimeGreen",
    "Linen", "Magenta", "Maroon",
    "MediumAquaMarine", "MediumBlue", "MediumOrchid",
    "MediumPurple", "MediumSeaGreen", "MediumSlateBlue",
    "MediumSpringGreen", "MediumTurquoise", "MediumVioletRed",
    "MidnightBlue", "MintCream", "MistyRose",
    "Moccasin", "NavajoWhite", "Navy",
    "OldLace", "Olive", "OliveDrab",
    "Orange", "OrangeRed", "Orchid",
    "PaleGoldenRod", "PaleGreen", "PaleTurquoise",
    "PaleVioletRed", "PapayaWhip", "PeachPuff",
    "Peru", "Pink", "Plum",
    "PowderBlue", "Purple", "RebeccaPurple",
    "Red", "RosyBrown", "RoyalBlue",
    "SaddleBrown", "Salmon", "SandyBrown",
    "SeaGreen", "SeaShell", "Sienna",
    "Silver", "SkyBlue", "SlateBlue",
    "SlateGray", "Snow", "SpringGreen",
    "SteelBlue", "Tan", "Teal",
    "Thistle", "Tomato", "Turquoise",
    "Violet", "Wheat", "White",
    "WhiteSmoke", "Yellow", "YellowGreen"
];
